#!/bin/bash

sleep 10

echo creating .env file

echo '
APP_NAME=${APP_NAME}
APP_ENV=local
APP_KEY=base64:BHkJQvbYWxPUWdU2qZU3ioiJScQrNmR6y8cuEmAyQcs=
APP_DEBUG=true
APP_URL=${APP_URL}

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=${DB_CONNECTION}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

API_URL_SHEETMUSIC=${API_URL_SHEETMUSIC}
API_URL_INSTRUMENTLIBRARY=${API_URL_INSTRUMENTLIBRARY}
API_URL_MESSAGESERVICE=${API_URL_MESSAGESERVICE}
API_URL_EVENTBOOKING=${API_URL_EVENTBOOKING}
API_URL_MUSICSESSION=${API_URL_MUSICSESSION}
API_URL_TUNERSERVICE=${API_URL_TUNERSERVICE}
' > .env

php artisan migrate --force
php artisan db:seed

npm run dev & php artisan serve --port=80 --host=0.0.0.0 --env=.env

exec docker-php-entrypoint "$@"