/**
 * @fileoverview gRPC-Web generated client stub for messageservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: protobuf.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.messageservice = require('./protobuf_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.messageservice.MessageServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.messageservice.MessageServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.messageservice.ClientMessage,
 *   !proto.messageservice.StatusResponse>}
 */
const methodDescriptor_MessageService_sendMessageToUser = new grpc.web.MethodDescriptor(
  '/messageservice.MessageService/sendMessageToUser',
  grpc.web.MethodType.UNARY,
  proto.messageservice.ClientMessage,
  proto.messageservice.StatusResponse,
  /**
   * @param {!proto.messageservice.ClientMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.messageservice.StatusResponse.deserializeBinary
);


/**
 * @param {!proto.messageservice.ClientMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.messageservice.StatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.messageservice.StatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.messageservice.MessageServiceClient.prototype.sendMessageToUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/messageservice.MessageService/sendMessageToUser',
      request,
      metadata || {},
      methodDescriptor_MessageService_sendMessageToUser,
      callback);
};


/**
 * @param {!proto.messageservice.ClientMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.messageservice.StatusResponse>}
 *     Promise that resolves to the response
 */
proto.messageservice.MessageServicePromiseClient.prototype.sendMessageToUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/messageservice.MessageService/sendMessageToUser',
      request,
      metadata || {},
      methodDescriptor_MessageService_sendMessageToUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.messageservice.User,
 *   !proto.messageservice.StreamMessage>}
 */
const methodDescriptor_MessageService_openMessageStream = new grpc.web.MethodDescriptor(
  '/messageservice.MessageService/openMessageStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.messageservice.User,
  proto.messageservice.StreamMessage,
  /**
   * @param {!proto.messageservice.User} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.messageservice.StreamMessage.deserializeBinary
);


/**
 * @param {!proto.messageservice.User} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.messageservice.StreamMessage>}
 *     The XHR Node Readable Stream
 */
proto.messageservice.MessageServiceClient.prototype.openMessageStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/messageservice.MessageService/openMessageStream',
      request,
      metadata || {},
      methodDescriptor_MessageService_openMessageStream);
};


/**
 * @param {!proto.messageservice.User} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.messageservice.StreamMessage>}
 *     The XHR Node Readable Stream
 */
proto.messageservice.MessageServicePromiseClient.prototype.openMessageStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/messageservice.MessageService/openMessageStream',
      request,
      metadata || {},
      methodDescriptor_MessageService_openMessageStream);
};


module.exports = proto.messageservice;

