services:
  SheetMusicAPI:
    build:
      context: .
    image: larsgielen/sheetmusicapi:1.0
    ports:
      - 5050:80
    environment:
      DB_HOST: db
      DB_PORT: 5055
      DB_ROOT_PASSWORD: root
      DB_ROOT_USER: root
      SERVICE__HOST_NAME: localhost
      SERVICE__HOST_PORT: 5050

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 5055:80
    environment:
      - PMA_ARBITRARY=1